# Generated by Django 5.2.8 on 2025-12-04 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriguide_ai', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerprofile',
            name='crops_grown',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='farm_name',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='farm_size',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='farming_method',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='region',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='years_of_experience',
        ),
    ]
