# Generated by Django 5.2.8 on 2025-11-10 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriguide_ai', '0002_communitypost_postcomment_postlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Tutorial title', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the tutorial')),
                ('category', models.CharField(choices=[('crops', 'Crops'), ('livestock', 'Livestock'), ('irrigation', 'Irrigation'), ('pest_control', 'Pest Control'), ('soil_management', 'Soil Management'), ('harvesting', 'Harvesting'), ('post_harvest', 'Post-Harvest'), ('farm_equipment', 'Farm Equipment'), ('marketing', 'Marketing'), ('other', 'Other')], default='other', help_text='Tutorial category', max_length=50)),
                ('video', models.FileField(help_text='Tutorial video file', upload_to='tutorials/videos/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Optional thumbnail image for the video', null=True, upload_to='tutorials/thumbnails/')),
                ('view_count', models.IntegerField(default=0, help_text='Number of views')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploader', models.ForeignKey(help_text='User who uploaded the tutorial', on_delete=django.db.models.deletion.CASCADE, related_name='tutorials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tutorials',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='tutorials_created_9d7d6f_idx'), models.Index(fields=['category'], name='tutorials_categor_92ea38_idx'), models.Index(fields=['uploader'], name='tutorials_uploade_376c00_idx')],
            },
        ),
    ]
