# Generated by Django 5.2.8 on 2025-11-10 14:37

import agriguide_ai.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriguide_ai', '0003_tutorial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypost',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for the post', null=True, storage=agriguide_ai.storage_backends.CommunityPostImageStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='extensionworkerprofile',
            name='verification_document',
            field=models.FileField(blank=True, null=True, storage=agriguide_ai.storage_backends.VerificationDocumentStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Optional thumbnail image for the video', null=True, storage=agriguide_ai.storage_backends.TutorialThumbnailStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='video',
            field=models.FileField(help_text='Tutorial video file', storage=agriguide_ai.storage_backends.TutorialVideoStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=agriguide_ai.storage_backends.ProfilePictureStorage(), upload_to=''),
        ),
    ]
