# Generated by Django 5.2.8 on 2025-11-18 13:37

import agriguide_ai.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriguide_ai', '0004_alter_communitypost_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image attachment', null=True, storage=agriguide_ai.storage_backends.ChatImageStorage(), upload_to=''),
        ),
    ]
